vege_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DATASET_PREFIX', 'vege') }}_{{ env_var('ENVIRONMENT', 'dev') }}"
      threads: 4
      timeout_seconds: 300
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DATASET_PREFIX', 'vege') }}_prod"
      threads: 8
      timeout_seconds: 300
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"